language: php
php:
- 5.6
cache:
  directories:
  - $HOME/.composer
install:
- composer install
script:
- ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
after_script:
- ./vendor/bin/codacycoverage clover
sudo: false
